FROM centos

RUN yum install wget -y
RUN yum install java-11-openjdk.x86_64 
RUN sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
RUN sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
RUN yum install jenkins -y
RUN yum echo -e "jenkins ALL=(ALL) NOPASSWD: ALL" >>/etc/sudoers
EXPOSE 8080
CMD sudo service jenkins start -DEFOREGROUND && /bin/bash
CMD ["java","-jar","/usr/lib/jenkins/jenkins.war"]